### ISSUE TITLE
Question: Can inventory file use variables to change behavior?

### ISSUE THREAD

**Issue by jeliker** [oracle/oci-ansible-collection#123]
I would like to parameterize my inventory file for example to override caching behavior.

```
. . . 

cache="{{ inventory_cache | default('yes') | bool }}"
cache_plugin: jsonfile
cache_timeout: "{{ inventory_cache_timeout | default(14400) | int }}"
cache_connection: /tmp/oci-cache
cache_prefix: "{{ inventory_cache_prefix | mandatory }}"

. . .

```

This doesn't seem to work as I would hope so am asking if it's supported in any way (otherwise I am just making errors while testing!).

**Comment by dineshsuthar786** [comment]
Thanks for reporting this. we will check this and update you.

**Comment by dineshsuthar786** [comment]
@jeliker, Currently we do not support jinja expressions for cache options.

**Comment by manojmeda** [comment]
@jeliker The cache plugin options are provided by ansible framework and not specific to OCI inventory plugin. I would recommend you check the individual cache plugin documentation for the supported features. Closing this issue since this is not controlled by OCI inventory plugin. Please feel free to reopen if you have any other queries.
