### ISSUE TITLE
oci_compute_volume_attachment_facts gets Linux iscsi attach commands for both Linux and Windows

### ISSUE THREAD

**Issue by AndreasFrangopoulos** [oracle/oci-ansible-collection#15]
Small bug, not really a problem since I will be constructing the join commands from other output but maybe one for the backlog:
When using the oci_compute_volume_attachment_facts module, it outputs Linux iscsi connect commands for Windows attached Block Volumes.
In contrast to the Console which shows the PowerShell commands.

**Comment by slmjy** [comment]
Also had to construct the commands manually

**Comment by manojmeda** [comment]
@AndreasFrangopoulos @slmjy Apologise for the delay in response. We are working on this and will try to include this in the next release.

**Comment by manojmeda** [comment]
@AndreasFrangopoulos @slmjy We updated the `oci_compute_volume_attachment` and `oci_compute_volume_attachment_facts` modules to return the powershell commands for windows systems. In `oci_compute_volume_attachment_facts`, we return the powershell commands only when getting the details of a specific volume attachment using `volume_attachment_id`. But when you list all the attachments, you would still get the default linux commands. We had to go with this because fetching the OS information needs additional API calls and doing that for list would create a lot of API requests which might not be what you want. For now the workaround is to call the module with `volume_attachment_id` to get the correct OS specific commands. Please check.

**Comment by AndreasFrangopoulos** [comment]
@manojmeda , Makes sense. Thanks!
