### ISSUE TITLE
fetch_db_host does not work with defined_tags filter

### ISSUE THREAD

**Issue by esutiatech** [oracle/oci-ansible-collection#47]
## Issue Report

When using oracle.oci.oci plugin with fetch_db_hosts and defined_tags it is not possible to fetch db systems and instances. Following .yml file is used for oracle.oci.oci plugin:

plugin: oracle.oci.oci
config_file: ~/.oci/config
config_profile: DEFAULT
regions:
  - eu-frankfurt-1
hostname_format: fqdn
filters:
- defined_tags: { "ansible": {"enabled": "true", "env_type": "preprod"} }
#- lifecycle_state: "RUNNING"
- lifecycle_state: 
when: ("RUNNING") or ("AVAILABLE")
fetch_db_hosts: true
debug: true 

**Expected behavior**

oracle.oci.oci plugin adds db systems and instances to inventory

**Environment**

* OS version: Ubuntu 20.04

* Ansible version:

    ansible --version
    2.10.4

* OCI Python SDK version:

    output of `python -c "import oci;print(oci.__version__)"`
    2.26.0

* OCI Ansible Modules version:

    insert output of (for oracle.oci):
`ansible-galaxy collection list`
    oracle.oci 2.14.0

**Comment by manojmeda** [comment]
@esutiatech Thanks for bringing this to our notice. Yes, we recently updated the documentation regarding the same. PFB the note from the documentation:

```
Note: defined_tags and freeform_tags filters are not supported for db hosts. The db hosts will not be returned when you use either of these filters.
```

The issue here is that the tags are not directly assigned to the db hosts(nodes) as you can see in the API reference (https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/DbNode/). One option is to infer the tags from the parent resource but db_system, db_home, database can have different tags. Also there is a possibility that db nodes supporting tags in the future. I will have to confirm with the DBAAS team before supporting the filter. Meanwhile, the work around is to fetch all the db hosts (without the filters) and do post processing.

**Comment by kostasns** [comment]
@manojmeda thanks for the update. At this point in time workaround does sound cumbersome, given that .py script works as expected. Will wait for the update from DBAAS team. Thanks again.

**Comment by manojmeda** [comment]
@esutiatech @kostasns Got response from the DBAAS team. They said we cannot use tags of parent resources for the db nodes. Also there is a possibility of db nodes supporting tags in the future. So for now I don't think we can support filtering db nodes using tags.

**Comment by kostasns** [comment]
Understood thanks.
